name: app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  riverpod_annotation: ^2.6.1
  flutter_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
